git:
  path: github.com/mephux/kolide
  branch: master

clone:
  depth: 32767

build:
  image: mephux/docker-golang
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - go get -u github.com/golang/lint/golint
    - go get github.com/jteeuwen/go-bindata/...
    - go get github.com/elazarl/go-bindata-assetfs/...
    - make
    - ./bin/kolide --version
    # - make package
    # - bash -x ./scripts/package.sh
