git:
  path: github.com/mephux/kolide
  branch: master

clone:
  depth: 32767

build:
  image: mephux/docker-golang
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - make
    - ./bin/kolide --version
    # - make package
    # - bash -x ./scripts/package.sh
